# -*- mode: python -*-
"""PyInstaller spec for the Windows build.

Run from the repository root:
    pyinstaller --clean --noconfirm packaging/windows/toolshed.spec

Two executables are produced from one Analysis. See the comment on exe_console.
"""

import sys
from pathlib import Path

REPO = Path(SPECPATH).resolve().parents[1]
sys.path.insert(0, str(REPO / "packaging"))

from _spec_common import DATA_DIRS, OTHER_EXCLUDES, QT_EXCLUDES, TREE_EXCLUDES

data_trees = [
    Tree(str(REPO / name), prefix=name, excludes=TREE_EXCLUDES) for name in DATA_DIRS
]

# Generated by the build workflow from toolshed.__version__ so the Properties
# tab shows a real version instead of 0.0.0.0. Optional for a local build.
version_file = REPO / "build" / "version_info.txt"

a = Analysis(
    [str(REPO / "packaging" / "entry.py")],
    pathex=[str(REPO)],
    binaries=[],
    datas=[],
    hiddenimports=[
        "keyring.backends.Windows",
        "keyring.backends.chainer",
        "keyring.backends.fail",
        # What keyring's Windows backend actually calls into.
        "win32ctypes.core",
    ],
    # hookspath: add packaging/hooks/ (with a real file in it) when a
    # custom hook is genuinely needed. An empty directory is not tracked
    # by git and would vanish on a fresh clone.
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=QT_EXCLUDES + OTHER_EXCLUDES,
    noarchive=False,
    optimize=0,
)

pyz = PYZ(a.pure)

_COMMON = dict(
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,          # see the Linux spec: UPX is an antivirus magnet
    upx_exclude=[],
    # With this True you get a "feature is disabled" dialog instead of a
    # traceback, which is strictly worse for a bug report.
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    contents_directory="_internal",
    icon=str(REPO / "packaging" / "windows" / "toolshed.ico"),
    version=str(version_file) if version_file.is_file() else None,
)

# What the user launches. console=False strips the console window -- and is
# precisely what sets sys.stdout/sys.stderr to None, which is why
# toolshed/_streams.py exists and why the build workflow smoke-tests this exe
# through a --report file rather than stdout.
exe_gui = EXE(
    pyz, a.scripts, [], exclude_binaries=True, name="toolshed", console=False, **_COMMON
)

# A second executable from the SAME Analysis, sharing one COLLECT. Costs about a
# megabyte and earns it twice over:
#   1. CI can read its output. A windowed exe has no stdout at all, so
#      `toolshed.exe --selftest > out.txt` produces an empty file.
#   2. Support. "Run toolshed-console.exe and paste what it says" is a question
#      a beginner can actually answer.
exe_console = EXE(
    pyz, a.scripts, [], exclude_binaries=True, name="toolshed-console", console=True, **_COMMON
)

coll = COLLECT(
    exe_gui,
    exe_console,
    a.binaries,
    a.datas,
    *data_trees,
    strip=False,
    upx=False,
    upx_exclude=[],
    name="toolshed",
)
