"""Draw the starter picture that ships with Toolshed.

Some workflows begin with a photo -- turning one into a 3D model, editing a
picture. Easy mode has to work on the first press of the button, so those need
something to start from before the user has chosen anything.

Shipping a photograph would mean shipping someone's copyright. This renders one
instead: a single rounded object on a plain surface, lit from one side, which
is exactly the kind of subject image-to-3D wants and about the simplest thing
that is not a flat colour.

Generated by a script rather than committed as a mystery blob, so anyone can
see where it came from and change it. Pure standard library -- no image library
is a dependency of this app, and adding one to draw a single file would be a
poor trade. Re-run with:

    python tools/make_starter_image.py
"""

from __future__ import annotations

import math
import struct
import zlib
from pathlib import Path

SIZE = 640
OUT = Path(__file__).resolve().parents[1] / "assets" / "starter-photo.png"

# The scene: one sphere resting on a plane, one light, a soft sky behind.
SPHERE_CENTRE = (0.0, 0.0, -3.2)
SPHERE_RADIUS = 1.0
GROUND_Y = -1.0
LIGHT = (-2.2, 3.0, -1.2)
SPHERE_COLOUR = (0.82, 0.36, 0.28)      # a warm terracotta
GROUND_COLOUR = (0.86, 0.85, 0.82)
SKY_TOP = (0.93, 0.94, 0.96)
SKY_BOTTOM = (0.80, 0.82, 0.85)


def normalise(v):
    length = math.sqrt(sum(c * c for c in v)) or 1.0
    return tuple(c / length for c in v)


def sphere_hit(origin, direction):
    """Distance along the ray to the sphere, or None."""
    ox, oy, oz = (o - c for o, c in zip(origin, SPHERE_CENTRE, strict=True))
    b = 2.0 * (ox * direction[0] + oy * direction[1] + oz * direction[2])
    c = ox * ox + oy * oy + oz * oz - SPHERE_RADIUS * SPHERE_RADIUS
    disc = b * b - 4.0 * c
    if disc < 0.0:
        return None
    root = math.sqrt(disc)
    for t in ((-b - root) / 2.0, (-b + root) / 2.0):
        if t > 1e-4:
            return t
    return None


def shade(point, normal, base):
    to_light = normalise(tuple(li - p for li, p in zip(LIGHT, point, strict=True)))
    lambert = max(0.0, sum(n * d for n, d in zip(normal, to_light, strict=True)))
    ambient = 0.28
    # A little specular so it reads as a solid object rather than a disc.
    view = normalise(tuple(-p for p in point))
    half = normalise(tuple(a + b for a, b in zip(to_light, view, strict=True)))
    spec = max(0.0, sum(n * h for n, h in zip(normal, half, strict=True))) ** 48
    return tuple(min(1.0, c * (ambient + 0.85 * lambert) + 0.35 * spec) for c in base)


def trace(direction):
    origin = (0.0, 0.0, 0.0)

    t = sphere_hit(origin, direction)
    if t is not None:
        point = tuple(o + d * t for o, d in zip(origin, direction, strict=True))
        normal = normalise(tuple(p - c for p, c in
                                 zip(point, SPHERE_CENTRE, strict=True)))
        return shade(point, normal, SPHERE_COLOUR)

    if direction[1] < -1e-4:                       # the ground plane
        t = (GROUND_Y - origin[1]) / direction[1]
        point = tuple(o + d * t for o, d in zip(origin, direction, strict=True))
        lit = shade(point, (0.0, 1.0, 0.0), GROUND_COLOUR)
        # Soft shadow: darken near where the sphere sits on the plane.
        dx = point[0] - SPHERE_CENTRE[0]
        dz = point[2] - SPHERE_CENTRE[2]
        shadow = math.exp(-((dx * dx + dz * dz) / 1.4))
        fog = min(1.0, max(0.0, (-point[2] - 2.0) / 9.0))
        lit = tuple(c * (1.0 - 0.55 * shadow) for c in lit)
        return tuple(c + (s - c) * fog for c, s in zip(lit, SKY_BOTTOM, strict=True))

    height = (direction[1] + 0.5)
    return tuple(b + (t - b) * max(0.0, min(1.0, height))
                 for t, b in zip(SKY_TOP, SKY_BOTTOM, strict=True))


def render() -> bytes:
    rows = bytearray()
    for y in range(SIZE):
        rows.append(0)                              # PNG filter: none
        for x in range(SIZE):
            # Two samples per axis. Enough to take the jaggies off the edge
            # without turning a build step into a coffee break.
            acc = [0.0, 0.0, 0.0]
            for sy in (0.25, 0.75):
                for sx in (0.25, 0.75):
                    u = (x + sx) / SIZE * 2.0 - 1.0
                    v = 1.0 - (y + sy) / SIZE * 2.0
                    colour = trace(normalise((u, v, -1.6)))
                    for i in range(3):
                        acc[i] += colour[i]
            for channel in acc:
                value = (channel / 4.0) ** (1 / 2.2)          # gamma
                rows.append(max(0, min(255, int(value * 255 + 0.5))))
    return bytes(rows)


def png(raw: bytes) -> bytes:
    def chunk(tag: bytes, data: bytes) -> bytes:
        return (struct.pack(">I", len(data)) + tag + data
                + struct.pack(">I", zlib.crc32(tag + data)))

    header = struct.pack(">IIBBBBB", SIZE, SIZE, 8, 2, 0, 0, 0)   # 8-bit RGB
    return (b"\x89PNG\r\n\x1a\n" + chunk(b"IHDR", header)
            + chunk(b"IDAT", zlib.compress(raw, 9)) + chunk(b"IEND", b""))


def main() -> None:
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_bytes(png(render()))
    print(f"wrote {OUT} ({OUT.stat().st_size / 1024:.0f} KB)")


if __name__ == "__main__":
    main()
